image:
    file: .gitpod.dockerfile

tasks:
  - name: nextjs
    init: |
      mkdir -p /workspace/data
      curl -fsSL https://bun.sh/install | bash && source ~/.bashrc 
      bun install
    command: |
      mongod --fork --logpath /var/log/mongod.log --dbpath /workspace/data
      bun dev
      
ports:
  - name: mognodb
    port: 27017
    onOpen: ignore
  - name: NEXT.JS
    port: 3000
    onOpen: open-browser