tasks:
  - name: nextjs
    init: |
      curl -fsSL https://bun.sh/install | bash && source ~/.bashrc 
      bun install
    command: |
      mkdir -p /workspace/data && mongod --dbpath /workspace/data --fork --logpath /workspace/data/mongod.log
      bun dev

ports:
  - name: mognodb
    port: 27017
    onOpen: ignore
  - name: mognodb-express
    port: 8081
    onOpen: open-browser
  - name: NEXT.JS
    port: 3000
    onOpen: open-browser