image: gitpod/workspace-bun

tasks:
  - name: nextjs
    init: |
      bun install
      docker compose pull
    command: |
      docker compose up -d
      bun dev

ports:
  - name: mognodb
    port: 27017
    onOpen: ignore
  - name: mognodb-express
    port: 8081  
    onOpen: open-browser
  - name: NEXT.JS
    port: 3000
    onOpen: open-browser