image:
    file: .gitpod.dockerfile

tasks:
  - init: |
      mkdir -p /workspace/data && mongod --dbpath /workspace/data
      curl -fsSL https://bun.sh/install | bash && source ~/.bashrc 
      bun install
    command: bun dev
