image:
    file: .gitpod.dockerfile

tasks:
  - name: nextjs
    init: |
      curl -fsSL https://bun.sh/install | bash && source ~/.bashrc 
      bun install
    command: bun dev
  - name: database
    command: mkdir -p /workspace/data && mongod --fork --dbpath /workspace/data

ports:
  - name: mognodb
    port: 27017
    onOpen: ignore
  - name: NEXT.JS
    port: 3000
    onOpen: open-browser