# .gitpod.yml

image:
  file: .gitpod.Dockerfile

tasks:
  - init: bun install
    command: |
      sudo service mongodb start
      mongo --eval 'db.runCommand({ connectionStatus: 1 })'
      bun dev
      sleep 5 && npx mongo-express

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
    - christian-kohler.npm-intellisense
    - dbaeumer.vscode-eslint
    - github.copilot
    - github.vscode-pull-request-github
    - naumovs.color-highlight
    - PKief.material-icon-theme

ports:
  - port: 3000
    onOpen: open-preview
  - port: 27017
    onOpen: ignore
  - port: 8081
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
